routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'EmployeeController@showTree')
    ->name('home');

Route::name('employee.')->middleware('auth')->group(function (){
    Route::get('manage', 'EmployeeController@manage')->name('manage');
    Route::post('employee', 'EmployeeController@store')->name('store');
    Route::get('employee/create', 'EmployeeController@create')->name('create');
    Route::delete('employee/{id}', 'EmployeeController@delete')->name('delete');
    Route::get('employee/{id}/edit', 'EmployeeController@edit')->name('edit');
    Route::put('employee/{id}', 'EmployeeController@update')->name('update');
    Route::get('employee/{id}', 'EmployeeController@show')->name('show');

    Route::get('move', 'EmployeeMoveController@show')->name('move.show');
    Route::post('move', 'EmployeeMoveController@move')->name('move');
});


Route::prefix('ajax')->name('ajax.')->middleware('auth')->group( function (){
    Route::get('employee/list', 'EmployeeController@getEmployeesForAjaxList')
        ->name('employee.list');

    Route::any('employee/{id}/remove-avatar', 'EmployeeController@removeAvatar')
        ->name('employee.remove.avatar');
});

Route::get('ajax/employee/tree', 'EmployeeController@getEmployeeNode')
    ->name('ajax.employee.tree');

Auth::routes();


Route::get('thumbnail/{template}','EmployeeController@getThumbnail')->name('image.thumbnail');

resources/views/mainmenu.blade.php
<nav class="navbar navbar-expand navbar-dark bg-primary">
    <a class="navbar-brand" href="{{route('home')}}">Test Assignment</a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{{route('home')}}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Staff</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{{route('employee.manage')}}">Manage</a>
                        <a class="dropdown-item" href="{{route('employee.create')}}">Add Employee</a>
                        <a class="dropdown-item" href="{{route('employee.move')}}">Reassign Supervisor</a>
                    </div>
            </li>
        </ul>
            @guest
                <div class="nav-item"><a class="btn btn-primary" href="{{route('login')}}">Login</a></div>
            @endguest
            @auth
                <span class="navbar-text">Hello, {{auth()->user()->name}}</span>
                <form class="form-inline" action="{{route('logout')}}" method="post">
                    @csrf
                    <button class="btn btn-primary ml-2"><i class="fa fa-sign-out" aria-hidden="true"></i>Logout</button>
                </form>
            @endauth
    </div>
</nav>

resources/views/template.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>Employee Catalog</title>
    <link rel="icon" href="{{asset('img/favicon.png')}}">
    <script src="{{asset('js/app.js')}}"></script>
    <link rel="stylesheet" href="{{asset('css/app.css')}}">
</head>
<body>
@include('mainmenu')
<div class="content container">
    @include('_partials.errors')
    @include('_partials.messages')
    <div class="row">
        @yield('content')
    </div>
</div>
@yield('scripts')
</body>
</html>