routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'EmployeeController@showTree')
    ->name('home');

Route::name('employee.')->middleware('auth')->group(function (){
    Route::get('manage', 'EmployeeController@manage')->name('manage');
    Route::post('employee', 'EmployeeController@store')->name('store');
    Route::get('employee/create', 'EmployeeController@create')->name('create');
    Route::delete('employee/{id}', 'EmployeeController@delete')->name('delete');
    Route::get('employee/{id}/edit', 'EmployeeController@edit')->name('edit');
    Route::put('employee/{id}', 'EmployeeController@update')->name('update');
    Route::get('employee/{id}', 'EmployeeController@show')->name('show');

    Route::get('move', 'EmployeeMoveController@show')->name('move.show');
    Route::post('move', 'EmployeeMoveController@move')->name('move');
});


Route::prefix('ajax')->name('ajax.')->middleware('auth')->group( function (){
    Route::get('employee/list', 'EmployeeController@getEmployeesForAjaxList')
        ->name('employee.list');

    Route::any('employee/{id}/remove-avatar', 'EmployeeController@removeAvatar')
        ->name('employee.remove.avatar');
});

Route::get('ajax/employee/tree', 'EmployeeController@getEmployeeNode')
    ->name('ajax.employee.tree');

Auth::routes();


Route::get('thumbnail/{template}','EmployeeController@getThumbnail')->name('image.thumbnail');

app/Employee.php
<?php

namespace App;

use App\Mapping\Mappable;
use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    use Mappable;

    public static $map = [
        'post' => 'position',
        'parent_id' => 'supervisor_id',
    ];

    const  DEFAULT_ORDER_FIELD = 'full_name';
    const  DEFAULT_DIRECTION = 'asc';

    protected $fillable = ['full_name', 'post', 'employment_date', 'salary', 'parent_id', 'avatar'];

    public $timestamps = false;

    protected $dates = ['employment_date'];

    protected $appends = ['text', 'has_children'];

    private static $searchable = [
        'employees.full_name',
        'employees.post',
        'employees.employment_date',
        'employees.salary',
        'supervisor.full_name',
    ];

    public static $sortable = [
        'full_name',
        'post',
        'employment_date',
        'salary',
        'supervisor_name',
    ];

    protected $casts = [
        'employment_date' => 'datetime:Y-m-d',
    ];

    public function getTextAttribute()
    {
        return "{$this->full_name} - {$this->post}";
    }

    public function getHasChildrenAttribute(): bool
    {
        return $this->children()->count();
    }

    public function supervisor()
    {
        return $this->belongsTo(Employee::class, 'parent_id');
    }

    public function children()
    {
        return $this->hasMany(Employee::class, 'parent_id');
    }

    public static function search(string $text, ?array $searchFields = null)
    {
        $query =  self::query();

        if (!mb_strlen($text)) {
            return $query;
        }

        $searchFields = $searchFields
            ? $searchFields
            : self::$searchable;

        $query->where(function ($q) use ($text, $searchFields) {
            foreach ($searchFields as $field) {
                if (in_array($field, self::$searchable)) {
                    $q->orWhere($field, 'like', "%$text%");
                }
            }
        });

        return $query;
    }

    public function toArray()
    {
        $data = parent::toArray();

        return $this->mapDirect($data, self::$map);
    }

}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Traits\EmployeeAjaxLists;
use App\Http\Controllers\Traits\EmployeeAvatar;
use App\Repositories\EmployeeRepository;
use Illuminate\Pagination\LengthAwarePaginator;

class EmployeeController extends Controller
{
    use EmployeeAvatar;
    use EmployeeAjaxLists;

    const COUNT_PER_PAGE = 8;
    const AVATAR_FOLDER = 'avatars';

    /**
     * @var EmployeeRepository
     */
    private $repository;

    private $rules = [
        'full_name' => ['required', 'max:255', 'min:3'],
        'position' => ['required', 'max:255', 'min:3'],
        'supervisor_id' => ['nullable', 'exists:employees,id'],
        'employment_date' => ['nullable', 'date_format:Y-m-d'],
        'salary' => ['required', 'numeric', 'min:0', 'max: 1000000'],
        'avatar' => ['image', 'max: 2048']
    ];

    public function __construct(EmployeeRepository $repository)
    {
        $this->repository = $repository;
    }

    public function showTree()
    {
        return view('employee.ajax-tree', compact('tree'));
    }

    public function create()
    {
        return view('employee.create')->with('employee', []);
    }

    public function delete($id)
    {
        $employee = $this->repository->findOrFail($id);

        $this->repository->delete($id);

        if ($employee['avatar']) {
            $this->deleteAvatarFile($employee['avatar']);
        }

        return redirect()->route('employee.manage')->with('message', trans('messages.delete_success'));
    }

    public function show($id)
    {
        $employee = $this->repository->findOrFail($id);

        return view('employee.show', compact('employee'));
    }


    public function store()
    {
        $this->validate(request(), $this->rules);

        $data = request()->all();

        $data['avatar'] = $this->processAvatarUpload();

        $this->repository->create($data);

        return redirect()->route('employee.manage')->with('message', trans('messages.create_success'));
    }

    public function edit($id)
    {
        $employee = $this->repository->findOrFail($id);

        return view('employee.edit', compact('employee'));
    }

    public function update($id)
    {
        $this->validate(request(), $this->rules);
        $data = request()->all();
        $data['avatar'] = $this->processAvatarUpload();

        $this->repository->update($id, $data);

        return redirect()->route('employee.manage')->with('message', trans('messages.update_success'));
    }

    public function manage()
    {

        $page = request()->get('page', 1);

        $employees = $this->repository->getEmployeeList(
            $page,
            self::COUNT_PER_PAGE,
            request('search'),
            null,
            request('order_by'),
            request('direction')
        );

        $paginator = $this->constructPaginator($page, $employees['total']);

        $employees = $employees['results'];

        if (request()->ajax()) {
            return view('employee.ajax-list', compact('employees', 'paginator', 'page'));
        }

        return view('employee.manage', compact('employees', 'paginator', 'page'));
    }

    protected function constructPaginator($page, $total): LengthAwarePaginator
    {
        $paginator = new LengthAwarePaginator([], $total, self::COUNT_PER_PAGE, $page);

        $paginator
            ->withPath(route('employee.manage'))
            ->appends(request()->except('page'));

        return $paginator;
    }


}

resources/views/employee/partials/form.blade.php
<div class="col-12">
    <form action="{{$action}}" method="post" enctype="multipart/form-data">
        {{ csrf_field() }}
        {{method_field($method)}}

        <div class="form-group">
            <label for="full-name">Avatar</label>
            <input class="dropify" type="file" name="avatar" data-height="200" data-default-file="@if(array_get($employee, 'avatar')){{asset('/storage/'.$employee['avatar'])}}@else{{old('avatar', asset('img/avatars/default.jpg'))}}@endif">
        </div>

        <div class="form-group">
            <label for="full-name">Full Name</label>
            <input type="text" class="form-control" name="full_name" id="full-name" placeholder="Full Name"
                   value="{{ old('full_name', array_get($employee, 'full_name'))}}">
        </div>
        <div class="form-group">
            <label for="post">Position</label>
            <input type="text" class="form-control" name="position" id="post" placeholder="Position"
                   value="{{old('position', array_get($employee, 'position'))}}">
        </div>
        <div class="form-group">
            <label for="start-date">Start Date</label>
            <input type="text" class="form-control" name="employment_date" id="start-date" placeholder="Y-m-d"
                   value="{{old('employment_date', array_get($employee, 'employment_date'))}}">
        </div>
        <div class="form-group">
            <label for="salary">Salary</label>
            <input type="number" min="0" step="0.01" placeholder="0.00" class="form-control" name="salary" id="salary"
                   value="{{old('salary', array_get($employee, 'salary'))}}">
        </div>
        <div class="form-group">
            <label for="supervisor">Supervisor</label>
            <select id="supervisor" name="supervisor_id" class="form-control select2">
                <option></option>
            </select>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary my-3 w-25 float-right"><i class="fa fa-save pr-1"></i>Save
            </button>
        </div>
    </form>
</div>

resources/views/employee/partials/form_scripts.blade.php
<script>
    $('#start-date').datetimepicker({format: 'Y-m-d', timepicker: false});

    loadSelectList(
        '{{route('ajax.employee.list')}}',
        '#supervisor',
        '{{old('supervisor_id', array_get($employee, 'supervisor_id'))}}'
    );

    @if(array_get($employee,'id'))
        initFileUploader(
            '.dropify',
            '{{route('ajax.employee.remove.avatar', array_get($employee,'id'))}}',
            {'_token': '{{ csrf_token() }}'},
        );
    @else
        initFileUploader('.dropify');
    @endif

</script>