routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'EmployeeController@showTree')
    ->name('home');

Route::name('employee.')->middleware('auth')->group(function (){
    Route::get('manage', 'EmployeeController@manage')->name('manage');
    Route::post('employee', 'EmployeeController@store')->name('store');
    Route::get('employee/create', 'EmployeeController@create')->name('create');
    Route::delete('employee/{id}', 'EmployeeController@delete')->name('delete');
    Route::get('employee/{id}/edit', 'EmployeeController@edit')->name('edit');
    Route::put('employee/{id}', 'EmployeeController@update')->name('update');
    Route::get('employee/{id}', 'EmployeeController@show')->name('show');

    Route::get('move', 'EmployeeMoveController@show')->name('move.show');
    Route::post('move', 'EmployeeMoveController@move')->name('move');
});


Route::prefix('ajax')->name('ajax.')->middleware('auth')->group( function (){
    Route::get('employee/list', 'EmployeeController@getEmployeesForAjaxList')
        ->name('employee.list');

    Route::any('employee/{id}/remove-avatar', 'EmployeeController@removeAvatar')
        ->name('employee.remove.avatar');
});

Route::get('ajax/employee/tree', 'EmployeeController@getEmployeeNode')
    ->name('ajax.employee.tree');

Auth::routes();


Route::get('thumbnail/{template}','EmployeeController@getThumbnail')->name('image.thumbnail');

app/Employee.php
<?php

namespace App;

use App\Mapping\Mappable;
use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    use Mappable;

    public static $map = [
        'post' => 'position',
        'parent_id' => 'supervisor_id',
    ];

    const  DEFAULT_ORDER_FIELD = 'full_name';
    const  DEFAULT_DIRECTION = 'asc';

    protected $fillable = ['full_name', 'post', 'employment_date', 'salary', 'parent_id', 'avatar'];

    public $timestamps = false;

    protected $dates = ['employment_date'];

    protected $appends = ['text', 'has_children'];

    private static $searchable = [
        'employees.full_name',
        'employees.post',
        'employees.employment_date',
        'employees.salary',
        'supervisor.full_name',
    ];

    public static $sortable = [
        'full_name',
        'post',
        'employment_date',
        'salary',
        'supervisor_name',
    ];

    protected $casts = [
        'employment_date' => 'datetime:Y-m-d',
    ];

    public function getTextAttribute()
    {
        return "{$this->full_name} - {$this->post}";
    }

    public function getHasChildrenAttribute(): bool
    {
        return $this->children()->count();
    }

    public function supervisor()
    {
        return $this->belongsTo(Employee::class, 'parent_id');
    }

    public function children()
    {
        return $this->hasMany(Employee::class, 'parent_id');
    }

    public static function search(string $text, ?array $searchFields = null)
    {
        $query =  self::query();

        if (!mb_strlen($text)) {
            return $query;
        }

        $searchFields = $searchFields
            ? $searchFields
            : self::$searchable;

        $query->where(function ($q) use ($text, $searchFields) {
            foreach ($searchFields as $field) {
                if (in_array($field, self::$searchable)) {
                    $q->orWhere($field, 'like', "%$text%");
                }
            }
        });

        return $query;
    }

    public function toArray()
    {
        $data = parent::toArray();

        return $this->mapDirect($data, self::$map);
    }

}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Traits\EmployeeAjaxLists;
use App\Http\Controllers\Traits\EmployeeAvatar;
use App\Repositories\EmployeeRepository;
use Illuminate\Pagination\LengthAwarePaginator;

class EmployeeController extends Controller
{
    use EmployeeAvatar;
    use EmployeeAjaxLists;

    const COUNT_PER_PAGE = 8;
    const AVATAR_FOLDER = 'avatars';

    /**
     * @var EmployeeRepository
     */
    private $repository;

    private $rules = [
        'full_name' => ['required', 'max:255', 'min:3'],
        'position' => ['required', 'max:255', 'min:3'],
        'supervisor_id' => ['nullable', 'exists:employees,id'],
        'employment_date' => ['nullable', 'date_format:Y-m-d'],
        'salary' => ['required', 'numeric', 'min:0', 'max: 1000000'],
        'avatar' => ['image', 'max: 2048']
    ];

    public function __construct(EmployeeRepository $repository)
    {
        $this->repository = $repository;
    }

    public function showTree()
    {
        return view('employee.ajax-tree', compact('tree'));
    }

    public function create()
    {
        return view('employee.create')->with('employee', []);
    }

    public function delete($id)
    {
        $employee = $this->repository->findOrFail($id);

        $this->repository->delete($id);

        if ($employee['avatar']) {
            $this->deleteAvatarFile($employee['avatar']);
        }

        return redirect()->route('employee.manage')->with('message', trans('messages.delete_success'));
    }

    public function show($id)
    {
        $employee = $this->repository->findOrFail($id);

        return view('employee.show', compact('employee'));
    }


    public function store()
    {
        $this->validate(request(), $this->rules);

        $data = request()->all();

        $data['avatar'] = $this->processAvatarUpload();

        $this->repository->create($data);

        return redirect()->route('employee.manage')->with('message', trans('messages.create_success'));
    }

    public function edit($id)
    {
        $employee = $this->repository->findOrFail($id);

        return view('employee.edit', compact('employee'));
    }

    public function update($id)
    {
        $this->validate(request(), $this->rules);
        $data = request()->all();
        $data['avatar'] = $this->processAvatarUpload();

        $this->repository->update($id, $data);

        return redirect()->route('employee.manage')->with('message', trans('messages.update_success'));
    }

    public function manage()
    {

        $page = request()->get('page', 1);

        $employees = $this->repository->getEmployeeList(
            $page,
            self::COUNT_PER_PAGE,
            request('search'),
            null,
            request('order_by'),
            request('direction')
        );

        $paginator = $this->constructPaginator($page, $employees['total']);

        $employees = $employees['results'];

        if (request()->ajax()) {
            return view('employee.ajax-list', compact('employees', 'paginator', 'page'));
        }

        return view('employee.manage', compact('employees', 'paginator', 'page'));
    }

    protected function constructPaginator($page, $total): LengthAwarePaginator
    {
        $paginator = new LengthAwarePaginator([], $total, self::COUNT_PER_PAGE, $page);

        $paginator
            ->withPath(route('employee.manage'))
            ->appends(request()->except('page'));

        return $paginator;
    }


}

resources/views/employee/ajax-list.blade.php
<div class="row">
    <div class="col">
        <table class="table table-striped">
            <thead class="thead-dark">
            <tr>
                <th>Avatar</th>
                <th>Full Name @include('_partials.sort',['route' => 'employee.manage', 'field' => 'full_name'])</th>
                <th>Position @include('_partials.sort',['route' => 'employee.manage', 'field' => 'post'])</th>
                <th>Start
                    Date @include('_partials.sort',['route' => 'employee.manage', 'field' => 'employment_date'])</th>
                <th>Salary @include('_partials.sort',['route' => 'employee.manage', 'field' => 'salary'])</th>
                <th>
                    Supervisor @include('_partials.sort',['route' => 'employee.manage', 'field' => 'supervisor_name'])</th>
                <th>Action</th>
            </tr>
            </thead>
            <tbody>
            @foreach($employees as $employee)
                <tr>
                    <td><img height="45" width="45" src="@if($employee['avatar']){{route('image.thumbnail',['45x45', 'file' => '/storage/'.$employee['avatar']])}}@else{{asset('img/avatars/default-small.jpg')}}@endif"
                             alt="ava">
                    </td>
                    <td><a href="{{route('employee.show',$employee['id'])}}">{{$employee['full_name']}}</a></td>
                    <td>{{$employee['position']}}</td>
                    <td>{{$employee['employment_date']}}</td>
                    <td>{{$employee['salary']}}$</td>
                    <td>{{array_get($employee, 'supervisor_name')}}</td>
                    <td>
                        <a href="{{route('employee.edit', $employee['id'])}}" class="pr-2"><i
                                    class="fa fa-lg fa-pencil-square"></i></a>
                        <form class="d-inline-block" method="post"
                              action="{{route('employee.delete', $employee['id'])}}">
                            @csrf
                            @method('delete')
                            <a class="action-confirm" data-message="@lang('messages.delete_confirmation', ['record' => $employee['full_name']])"
                               href="javascript:void(0);"><i class="fa fa-lg fa-remove" aria-hidden="true"></i>
                            </a>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
</div>
<div class="row">
    <div class="col text-center">
        {{$paginator->links()}}
    </div>
</div>

<script>
    $('.pagination a, .sort').click(function (e) {
        e.preventDefault();
        let link = $(e.target);
        if (!link.is('a'))
            link = link.parent();
        let url = link.attr('href');
        loadAjaxList(url, '#employee-list');
    });

    initConfirmationDialog('.action-confirm')
</script>

resources/views/employee/ajax-tree.blade.php
@extends('template')

@section('content')
    <div class="container">
        <h2>Employees Tree</h2>
        <div class="row">
            <div class="tree col" id="tree"></div>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
        initTree('#tree', '{{route('ajax.employee.tree',['lazy'])}}');
    </script>
@endsection

resources/views/employee/create.blade.php
@extends('template')

@section('content')
    <h2 class="content-title">Add new employee</h2>
    @include('employee.partials.form', ['action' => route('employee.store'), 'method' => 'post'])
@endsection

@section('scripts')
    @include('employee.partials.form_scripts')
@endsection

resources/views/employee/edit.blade.php
@extends('template')

@section('content')
    <h2 class="content-title">Edit Employee - {{$employee['full_name']}}</h2>
    @include('employee.partials.form', ['action' => route('employee.update', $employee['id']), 'method' => 'put'])
@endsection

@section('scripts')
    @include('employee.partials.form_scripts')
@endsection

resources/views/employee/manage.blade.php
@extends('template')
@section('content')

    <div class="col-md-6 offset-6 my-3">
        <form class="form-inline my-2 float-right">
            <input id="text-search" class="form-control mr-sm-2" type="search" placeholder="Search" name="search" aria-label="Search">
            <button id="btn-search" class="btn btn-outline-success my-2" type="submit">Search</button>
        </form>
    </div>

    <div id="employee-list" class="col-12">
        @include('employee.ajax-list')
    </div>

    <script>
        $('#btn-search').click(function (e) {
            e.preventDefault();
            let url = '{{route('employee.manage')}}' + '?search=' + $('#text-search').val();
            loadAjaxList(url, '#employee-list');
        })
    </script>
@endsection

resources/views/employee/move.blade.php
@extends('template')

@section('content')
    <h2 class="content-title">Assign Employees to new supervisor</h2>
    <div class="col-12">
        <form action="{{route('employee.move')}}" method="post">
            @csrf
            <div class="form-group">
                <label for="old_supervisor">Old Supervisor</label>
                <select id="old_supervisor" name="old_supervisor_id" class="form-control select2">
                    <option></option>
                </select>
                <div class="form-group">
                    <label for="new_supervisor">New Supervisor</label>
                    <select id="new_supervisor" name="new_supervisor_id" class="form-control select2">
                        <option></option>
                    </select>
                </div>
            </div>
            <button class="btn btn-primary float-right" type="submit">Reassign</button>
        </form>
    </div>
@endsection
@section('scripts')
    <script>
        loadSelectList('{{route('ajax.employee.list')}}', '#old_supervisor', '{{old('old_supervisor_id')}}');
        loadSelectList('{{route('ajax.employee.list')}}', '#new_supervisor', '{{old('new_supervisor_id')}}');
    </script>
@endsection

resources/views/employee/show.blade.php
@extends('template')

@section('content')
    <h2 class="content-title"></h2>
    <div class="col-12">
        <div class="card" >
            <div class="card-header">
                <div class="row">
                    <h2 class="col-8 mx-auto">{{$employee['full_name']}}</h2>
                    <div class="col-4"><img src="@if($employee['avatar']){{asset('/storage/'.$employee['avatar'])}}@else{{asset('img/avatars/default.jpg')}}@endif"
                                            alt="" height="100" width="100" class="float-right" style="max-height: 100px; max-width: 100px">
                    </div>
                </div>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <div class="row">
                        <label class="col-6 font-weight-bold">Position</label>
                        <p class="col-6">{{$employee['position']}}</p>
                    </div>

                </li>
                <li class="list-group-item">
                    <div class="row">
                        <label class="col-6 font-weight-bold">Salary</label>
                        <p class="col-6">{{$employee['salary']}}$</p>
                    </div>

                </li>
                <li class="list-group-item">
                    <div class="row">
                        <label class="col-6 font-weight-bold">Supervisor</label>
                        <p class="col-6">{{@$employee['supervisor']['full_name']}}</p>
                    </div>
                </li>

            </ul>
        </div>
    </div>
@endsection